PyTorch tutorial
Tutorials > Deep Learning with PyTorch: A 60 Minute Blitz > What is PyTorch?
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [60]:
from __future__ import print_function

In [5]:
import torch

In [6]:
x = torch.empty(5,3)
print(x)

tensor([[9.1837e-39, 4.6837e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 9.1837e-39]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.7987, 0.3019, 0.1868],
        [0.5501, 0.1992, 0.6952],
        [0.2053, 0.0267, 0.9133],
        [0.3263, 0.2358, 0.4575],
        [0.7135, 0.4388, 0.0607]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.7793, -0.9228, -0.0634],
        [-0.2224,  1.2842,  0.1896],
        [ 0.2226,  0.3611, -1.0621],
        [ 1.1406,  0.9657,  0.9217],
        [-0.2723, -0.1783,  2.2160]])


In [15]:
print(x.size()) # torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


In [19]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 1.7540,  0.0356,  0.0107],
        [ 0.5069,  1.6783,  0.8745],
        [ 0.8879,  0.8464, -0.0948],
        [ 1.7461,  1.4701,  1.3630],
        [-0.0123,  0.0157,  3.0451]])


In [20]:
print(torch.add(x, y))

tensor([[ 1.7540,  0.0356,  0.0107],
        [ 0.5069,  1.6783,  0.8745],
        [ 0.8879,  0.8464, -0.0948],
        [ 1.7461,  1.4701,  1.3630],
        [-0.0123,  0.0157,  3.0451]])


In [21]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 1.7540,  0.0356,  0.0107],
        [ 0.5069,  1.6783,  0.8745],
        [ 0.8879,  0.8464, -0.0948],
        [ 1.7461,  1.4701,  1.3630],
        [-0.0123,  0.0157,  3.0451]])


In [22]:
y.add_(x)
print(y)

tensor([[ 1.7540,  0.0356,  0.0107],
        [ 0.5069,  1.6783,  0.8745],
        [ 0.8879,  0.8464, -0.0948],
        [ 1.7461,  1.4701,  1.3630],
        [-0.0123,  0.0157,  3.0451]])


In [24]:
print(x[:, 1])

tensor([-0.9228,  1.2842,  0.3611,  0.9657, -0.1783])


In [29]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x, y, z)
print()
print(x.size(), y.size(), z.size())

tensor([[ 1.7542,  0.0435,  0.5095,  0.4139],
        [-0.3568,  0.4062, -0.7339, -0.5756],
        [-0.5226, -0.8363, -1.5732,  0.3778],
        [-0.4594, -1.1741,  1.0750,  1.9439]]) tensor([ 1.7542,  0.0435,  0.5095,  0.4139, -0.3568,  0.4062, -0.7339, -0.5756,
        -0.5226, -0.8363, -1.5732,  0.3778, -0.4594, -1.1741,  1.0750,  1.9439]) tensor([[ 1.7542,  0.0435,  0.5095,  0.4139, -0.3568,  0.4062, -0.7339, -0.5756],
        [-0.5226, -0.8363, -1.5732,  0.3778, -0.4594, -1.1741,  1.0750,  1.9439]])

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


NumPy Bridge

In [54]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [55]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [56]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [57]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a, type(a))
print(b, type(b))

[2. 2. 2. 2. 2.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.], dtype=torch.float64) <class 'torch.Tensor'>


CUDA Tensors

In [59]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!