In [1]:
import torch

In [101]:
x = torch.tensor([[2.,1.], [2., 3.]], requires_grad=True)
x

tensor([[2., 1.],
        [2., 3.]], requires_grad=True)

In [102]:
y = x.pow(2)
y

tensor([[4., 1.],
        [4., 9.]], grad_fn=<PowBackward0>)

In [103]:
z = y + 3
z

tensor([[ 7.,  4.],
        [ 7., 12.]], grad_fn=<AddBackward0>)

In [104]:
out = z.sum()

In [107]:
out.backward(retain_graph=True)

In [108]:
x.grad

tensor([[ 8.,  4.],
        [ 8., 12.]])